---
title: "Outreach activities"
---

## Outreach activities

### Media interviews

Axelrod, J. (2024, September 4). Germany’s Far Right Is in a Panic Over Telegram. *WIRED.* <https://www.wired.com/story/germanys-far-right-is-in-a-panic-over-telegram/>

Dorn, L. (2024). Rechtsextremer Wahlkampf auf Telegram – „Es funktioniert wie ein eigenes Medienoutlet“. *Weizenbaum News*. <https://www.weizenbaum-institut.de/news/detail/rechtsextremer-wahlkampf-auf-telegram-es-funktioniert-wie-ein-eigenes-medienoutlet/>

### Podcast

Die Vermessung des rechten Verschwörungs-Kosmos. *NEOVEX - Der Podcast*. 17.06.2024. <https://open.spotify.com/episode/6oz4lQ1Cx0nwNLsWD89GIv>\

### Blog posts

Zhang, X., Becker, J., Buehling, K., Heft, A.  (2024, December 18). Die Transnationalität rechtsextremer Verschwörungstheorien online und ihre länderspezifische Adaption. NEOVEX Blog. <https://neovex-projekt.de/die-transnationalitat-rechtsextremer-verschworungstheorien-online-und-ihre-landerspezifische-adaption/>

Buehling, K., Heft, A., Zhang, X. (2024, March 12). Der Ton macht die Musik – Die sprachlichen Finessen von Verschwörungserzählungen auf digitalen Plattformen. NEOVEX Blog. <https://neovex-projekt.de/der-ton-macht-die-musik-die-sprachlichen-finessen-von-verschwoerungserzaehlungen-auf-digitalen-plattformen/>

Buehling, K. (2023, July 5). How well can conspiracy theory content be measured on social media? It’s a matter of time! *DigiMoD Blog.* <https://digimod.weizenbaum-institut.de/how-well-can-conspiracy-theory-content-be-measured-on-social-media/>

Buehling, K. (2023, April 17). Wie gut kann man verschwörungstheoretische Inhalte auf Social Media messen? Alles eine Frage der Zeit! *NEOVEX Blog.* <https://neovex-projekt.de/wie-gut-kann-man-verschwoerungstheoretische-inhalte-auf-social-media-messen-alles-eine-frage-der-zeit/>

Buehling, K., & Heft, A. (2022, June 15). Wie wird die Verbreitung von Verschwörungstheorien gemessen? *NEOVEX Blog*. <https://neovex-projekt.de/2022/2541/>
