# This file controls the settings for your Quarto template from www.marvinschmitt.com

# website settings
website:
  title: "Dr. Kilian Buehling"                                # Your name
  description: "Information ecosystems, data science, and economics"   # A brief slogan (optional)
  image: img/my_image.jpg
  
  favicon: img/icon_l2.png
  
  # start of the navigation bar at the top of the website
  navbar:
    pinned: true
    logo: /img/icon_l2.png
    
    # your sub-pages
    left:
      - text: "About"
        href: about/index.qmd
      - text: "Research"
        href: research/index.qmd
      - text: "Data / Software"
        href: data_software/index.qmd
      - text: "Outreach"
        href: outreach/index.qmd
      - text: "Teaching"
        href: teaching/index.qmd
      - text: "CV"
        href: cv.pdf
    
  
  

# Don't touch unless you know what you are doing :) ------------
  search: 
    location: navbar
    type: textbox
  page-footer: 
    left: |
      <span class="faux-block">&#169; 2025 Kilian Buehling</span>
    
    right: |
      <span class="faux-block"><a>Cool stuff!</a></span>

project:
  type: website
  output-dir: docs

  preview: 
    port: 22222
    browser: true
    watch-inputs: true
    navigate: true

execute:
  freeze: true

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true